### ISSUE TITLE
Not working as a template

### ISSUE THREAD

**Issue by tgirod** [hoodiehq/hoodie-app-skeleton#17]
Following the tutorial, I've just tried to use this template to create a new hoodie app.

```
$ hoodie new myapp -t zoepage/hoodie-app-skeleton
$ cd myapp
$ hoodie start

[...]

Version: 0.6.3 (node v4.6.1, npm 2.15.11, platform: linux)
[hoodie] Could not start hoodie.
```

Hoodie silently fails, verbose mode does not give more information about the reason of this failure.

**Comment by gr2m** [comment]
see https://github.com/hoodiehq/documentation/issues/244#issuecomment-259599452
